application: ratecourse
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: endpoints_service.app
  secure: always

libraries:
- name: endpoints
  version: "1.0"